version: '3.9'

services:
  postgres:
    image: postgres:18-alpine
    container_name: flagmeter-postgres-dev
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
      -c shared_buffers=1GB
      -c effective_cache_size=4GB
      -c maintenance_work_mem=256MB
      -c work_mem=16MB
      -c wal_buffers=16MB
      -c max_wal_size=3GB
      -c min_wal_size=1GB
      -c checkpoint_timeout=900
      -c checkpoint_completion_target=0.9
      -c wal_compression=on
      -c synchronous_commit=off
      -c wal_writer_delay=200ms
      -c bgwriter_delay=200ms
      -c bgwriter_lru_maxpages=100
      -c bgwriter_lru_multiplier=2.0
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_connections=100
      -c max_worker_processes=4
      -c max_parallel_workers_per_gather=2
      -c max_parallel_workers=4
      -c autovacuum=on
      -c autovacuum_naptime=30s
      -c autovacuum_vacuum_cost_limit=1000
      -c autovacuum_max_workers=3
      -c autovacuum_vacuum_scale_factor=0.1
      -c autovacuum_analyze_scale_factor=0.05
      -c log_checkpoints=on
      -c log_lock_waits=on
      -c log_temp_files=0
    environment:
      POSTGRES_USER: flagmeter
      POSTGRES_PASSWORD: flagmeter
      POSTGRES_DB: flagmeter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flagmeter"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - flagmeter-dev

  valkey:
    image: valkey/valkey:7-alpine
    container_name: flagmeter-valkey-dev
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - flagmeter-dev

  prometheus:
    image: prom/prometheus:latest
    container_name: flagmeter-prometheus-dev
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_dev:/prometheus
    networks:
      - flagmeter-dev

  grafana:
    image: grafana/grafana:latest
    container_name: flagmeter-grafana-dev
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    ports:
      - "3001:3000"
    volumes:
      - grafana_data_dev:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    networks:
      - flagmeter-dev

  loki:
    image: grafana/loki:latest
    container_name: flagmeter-loki-dev
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data_dev:/loki
    networks:
      - flagmeter-dev

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: flagmeter-postgres-exporter-dev
    environment:
      DATA_SOURCE_NAME: "postgresql://flagmeter:flagmeter@postgres:5432/flagmeter?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - flagmeter-dev
    depends_on:
      postgres:
        condition: service_healthy

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: flagmeter-redis-exporter-dev
    environment:
      REDIS_ADDR: "valkey:6379"
    ports:
      - "9121:9121"
    networks:
      - flagmeter-dev
    depends_on:
      valkey:
        condition: service_healthy

volumes:
  postgres_data_dev:
  prometheus_data_dev:
  grafana_data_dev:
  loki_data_dev:

networks:
  flagmeter-dev:
    driver: bridge
