version: '3.9'

services:
  postgres:
    image: postgres:18-alpine
    container_name: flagmeter-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-flagmeter}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-flagmeter}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-flagmeter}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - flagmeter

  valkey:
    image: valkey/valkey:7-alpine
    container_name: flagmeter-valkey
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - flagmeter

  dashboard:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.dashboard
    container_name: flagmeter-dashboard
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-flagmeter}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-flagmeter}
      VALKEY_URL: redis://valkey:6379
      NODE_ENV: production
      QUEUE_NAME: events
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${DASHBOARD_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - flagmeter

  worker:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.worker
    container_name: flagmeter-worker
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-flagmeter}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-flagmeter}
      VALKEY_URL: redis://valkey:6379
      NODE_ENV: production
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-4}
      QUEUE_NAME: events
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      dashboard:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - flagmeter

  prometheus:
    image: prom/prometheus:latest
    container_name: flagmeter-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - flagmeter

  grafana:
    image: grafana/grafana:latest
    container_name: flagmeter-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL:-http://localhost:3001}
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped
    networks:
      - flagmeter

  loki:
    image: grafana/loki:latest
    container_name: flagmeter-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - flagmeter

volumes:
  postgres_data:
  valkey_data:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  flagmeter:
    driver: bridge
