# Swarm deployment configuration for FlagMeter - Observability Stack
# Deploy to: Swarm Manager node
# Uses Coolify's managed overlay network

version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - coolify-overlay
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
      labels:
        - coolify.managed=true
        - coolify.type=service

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL:-https://grafana.raus.cloud}
      GF_FEATURE_TOGGLES_ENABLE: publicDashboards
      GF_ALLOW_EMBEDDING: "true"
    networks:
      - coolify-overlay
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
      labels:
        - coolify.managed=true
        - coolify.type=service

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - coolify-overlay
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
      labels:
        - coolify.managed=true
        - coolify.type=service

# Use Coolify's existing overlay network
networks:
  coolify-overlay:
    external: true

# Coolify storage definitions
x-coolify:
  volumes:
    prometheus_data:
      name: prometheus_data
      driver: local
    grafana_data:
      name: grafana_data  
      driver: local
    loki_data:
      name: loki_data
      driver: local

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local
