# Coolify deployment configuration for FlagMeter - Observability Stack
# This file contains only the observability services
# 
# Optimized for: Hetzner CAX11 (ARM64, 2 vCPU, 4GB RAM)
# All images are ARM64 compatible

version: '1.0'

services:
  prometheus:
    build:
      dockerfile: infra/docker/Dockerfile.prometheus
      context: .
    ports:
      - 9090
    volumes:
      - prometheus_data:/prometheus
    environment:
      # Target the app services - update these URLs based on your deployment
      DASHBOARD_TARGET: ${DASHBOARD_TARGET:-dashboard:9464}
      WORKER_TARGET: ${WORKER_TARGET:-worker:9465}
      POSTGRES_TARGET: ${POSTGRES_TARGET:-postgres:5432}
      VALKEY_TARGET: ${VALKEY_TARGET:-valkey:6379}

  grafana:
    build:
      dockerfile: infra/docker/Dockerfile.grafana
      context: .
    ports:
      - 3001
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: false
      # Point to the observability services
      PROMETHEUS_URL: ${PROMETHEUS_URL:-http://prometheus:9090}
      LOKI_URL: ${LOKI_URL:-http://loki:3100}
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      # Update this to point to your app postgres instance
      DATA_SOURCE_NAME: ${DATABASE_URL:-postgresql://flagmeter:flagmeter123@postgres:5432/flagmeter?sslmode=disable}
    depends_on:
      - prometheus

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      # Update this to point to your app valkey instance
      REDIS_ADDR: ${VALKEY_ADDR:-valkey:6379}
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
  loki_data:

# Resource limits optimized for Hetzner CAX11 (ARM64, 2 vCPU, 4GB RAM)
resources:
  prometheus:
    memory: 256M      # Metrics storage and queries
    cpu: 0.2
  grafana:
    memory: 256M      # Dashboard visualization
    cpu: 0.2
  loki:
    memory: 128M      # Log aggregation
    cpu: 0.1
  postgres-exporter:
    memory: 64M       # PostgreSQL metrics exporter
    cpu: 0.05
  redis-exporter:
    memory: 64M       # Valkey/Redis metrics exporter
    cpu: 0.05
# Total: ~768MB RAM allocated, ~0.6GB CPU shares
# Can run on same server as app or separate instance
