# Swarm deployment configuration for FlagMeter - Application Stack
# Deploy to: Swarm Worker node
# Network: flagmeter-net (overlay)
#
# Build images first: ./scripts/build-and-deploy-swarm.sh

version: '3.8'

services:
  dashboard:
    image: flagmeter-dashboard:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://flagmeter:flagmeter123@postgres:5432/flagmeter}
      VALKEY_URL: ${VALKEY_URL:-redis://valkey:6379}
      LOKI_URL: ${LOKI_URL:-http://loki:3100}
      NODE_ENV: production
      QUEUE_NAME: events
      LOG_LEVEL: info
    networks:
      - flagmeter-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 1536M
          cpus: '1.0'

  worker:
    image: flagmeter-worker:latest
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://flagmeter:flagmeter123@postgres:5432/flagmeter}
      VALKEY_URL: ${VALKEY_URL:-redis://valkey:6379}
      LOKI_URL: ${LOKI_URL:-http://loki:3100}
      NODE_ENV: production
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-4}
      QUEUE_NAME: events
      LOG_LEVEL: info
    networks:
      - flagmeter-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 1024M
          cpus: '0.3'

  postgres:
    image: postgres:18-alpine
    command: >
      postgres
      -c shared_buffers=1GB
      -c effective_cache_size=4GB
      -c maintenance_work_mem=256MB
      -c work_mem=16MB
      -c wal_buffers=16MB
      -c max_wal_size=3GB
      -c min_wal_size=1GB
      -c checkpoint_timeout=900
      -c checkpoint_completion_target=0.9
      -c wal_compression=on
      -c synchronous_commit=off
      -c wal_writer_delay=200ms
      -c bgwriter_delay=200ms
      -c bgwriter_lru_maxpages=100
      -c bgwriter_lru_multiplier=2.0
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_connections=100
      -c max_worker_processes=4
      -c max_parallel_workers_per_gather=2
      -c max_parallel_workers=4
      -c autovacuum=on
      -c autovacuum_naptime=30s
      -c autovacuum_vacuum_cost_limit=1000
      -c autovacuum_max_workers=3
      -c autovacuum_vacuum_scale_factor=0.1
      -c autovacuum_analyze_scale_factor=0.05
      -c log_checkpoints=on
      -c log_lock_waits=on
      -c log_temp_files=0
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-flagmeter}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-flagmeter123}
      POSTGRES_DB: ${POSTGRES_DB:-flagmeter}
    networks:
      - flagmeter-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 1280M
          cpus: '0.6'

  valkey:
    image: valkey/valkey:7-alpine
    networks:
      - flagmeter-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 128M
          cpus: '0.05'

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER:-flagmeter}:${POSTGRES_PASSWORD:-flagmeter123}@postgres:5432/${POSTGRES_DB:-flagmeter}?sslmode=disable
    networks:
      - flagmeter-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 64M
          cpus: '0.05'

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      REDIS_ADDR: valkey:6379
    networks:
      - flagmeter-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 64M
          cpus: '0.05'

networks:
  flagmeter-net:
    name: obs_flagmeter-net
    external: true

volumes:
  postgres_data:
