# Coolify deployment configuration for FlagMeter
# This file enables auto-detection and configuration in Coolify
# 
# Optimized for: Hetzner CAX11 (ARM64, 2 vCPU, 4GB RAM)
# All images are ARM64 compatible

version: '1.0'

services:
  dashboard:
    name: flagmeter-dashboard
    build:
      dockerfile: infra/docker/Dockerfile.dashboard
      context: .
    ports:
      - 3000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - DATABASE_URL
      - VALKEY_URL
      - NODE_ENV=production
      - QUEUE_NAME=events
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - valkey

  worker:
    name: flagmeter-worker
    build:
      dockerfile: infra/docker/Dockerfile.worker
      context: .
    environment:
      - DATABASE_URL
      - VALKEY_URL
      - NODE_ENV=production
      - WORKER_CONCURRENCY=2
      - QUEUE_NAME=events
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - valkey

  postgres:
    name: flagmeter-postgres
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  valkey:
    name: flagmeter-valkey
    image: valkey/valkey:7-alpine

  prometheus:
    name: flagmeter-prometheus
    image: prom/prometheus:latest
    ports:
      - 9090
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    name: flagmeter-grafana
    image: grafana/grafana:latest
    ports:
      - 3001
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD

  loki:
    name: flagmeter-loki
    image: grafana/loki:latest
    ports:
      - 3100
    volumes:
      - loki_data:/loki

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  loki_data:

# Preview deployments configuration
previews:
  enabled: true
  pattern: pr-{number}
  domain: meter.yourdomain.com
  services:
    - dashboard
    - worker

# Resource limits optimized for Hetzner CAX11 (ARM64, 2 vCPU, 4GB RAM)
resources:
  dashboard:
    memory: 768M      # TanStack Start SSR + API routes
    cpu: 0.75
  worker:
    memory: 512M      # Event processing queue
    cpu: 0.5
  postgres:
    memory: 768M      # Main data store
    cpu: 0.5
  valkey:
    memory: 256M      # Event queue + cache
    cpu: 0.25
  prometheus:
    memory: 384M      # Metrics collection
    cpu: 0.25
  grafana:
    memory: 384M      # Dashboard visualization
    cpu: 0.25
  loki:
    memory: 256M      # Log aggregation
    cpu: 0.25
# Total: ~3.3GB RAM allocated, ~1.7GB CPU shares
# Leaves ~700MB for OS and buffers
